; Song ids are calculated by address to save space.

;music_const: MACRO
;\1 EQUS "((\2 - SFX_Headers_02) / 3)"
;ENDM
const_value = 1

    const MUSIC_PALLET_TOWN
	const MUSIC_POKECENTER
	const MUSIC_GYM
	const MUSIC_CITIES1
	const MUSIC_CITIES2
	const MUSIC_CELADON
	const MUSIC_CINNABAR
	const MUSIC_VERMILION
	const MUSIC_LAVENDER
	const MUSIC_SS_ANNE
	const MUSIC_MEET_PROF_OAK
	const MUSIC_MEET_RIVAL
	const MUSIC_MUSEUM_GUY
	const MUSIC_SAFARI_ZONE
	const MUSIC_PKMN_HEALED
	const MUSIC_ROUTES1
	const MUSIC_ROUTES2
	const MUSIC_ROUTES3
	const MUSIC_ROUTES4
	const MUSIC_INDIGO_PLATEAU
	
	const MUSIC_GYM_LEADER_BATTLE
	const MUSIC_TRAINER_BATTLE
	const MUSIC_WILD_BATTLE
	const MUSIC_FINAL_BATTLE
	const MUSIC_DEFEATED_TRAINER
	const MUSIC_DEFEATED_WILD_MON
	const MUSIC_DEFEATED_GYM_LEADER
	
	const MUSIC_TITLE_SCREEN
	const MUSIC_CREDITS
	const MUSIC_HALL_OF_FAME
	const MUSIC_OAKS_LAB
	const MUSIC_JIGGLYPUFF_SONG
	const MUSIC_BIKE_RIDING
	const MUSIC_SURFING
	const MUSIC_GAME_CORNER
	const MUSIC_INTRO_BATTLE
	const MUSIC_DUNGEON1
	const MUSIC_DUNGEON2
	const MUSIC_DUNGEON3
	const MUSIC_CINNABAR_MANSION
	const MUSIC_POKEMON_TOWER
	const MUSIC_SILPH_CO
	const MUSIC_MEET_EVIL_TRAINER
	const MUSIC_MEET_FEMALE_TRAINER
	const MUSIC_MEET_MALE_TRAINER


