MonsterNames: ; 1c21e (7:421e)
	db "BULBASAUR@"
	db "IVYSAUR@@@"
	db "VENUSAUR@@"
	db "CHARMANDER"
	db "CHARMELEON"
	db "CHARIZARD@"
	db "SQUIRTLE@@"
	db "WARTORTLE@"
	db "BLASTOISE@"
	db "CATERPIE@@"
	db "METAPOD@@@"
	db "BUTTERFREE"
	db "WEEDLE@@@@"
	db "KAKUNA@@@@"
	db "BEEDRILL@@"
	db "PIDGEY@@@@"
	db "PIDGEOTTO@"
	db "PIDGEOT@@@"
	db "RATTATA@@@"
	db "RATICATE@@"
	db "SPEAROW@@@"
	db "FEAROW@@@@"
	db "EKANS@@@@@"
	db "ARBOK@@@@@"
	db "PIKACHU@@@"
	db "RAICHU@@@@"
	db "SANDSHREW@"
	db "SANDSLASH@"
	db "NIDORAN♀@@"
	db "NIDORINA@@"
	db "NIDOQUEEN@"
	db "NIDORAN♂@@"
	db "NIDORINO@@"
	db "NIDOKING@@"
	db "CLEFAIRY@@"
	db "CLEFABLE@@"
	db "VULPIX@@@@"
	db "NINETALES@"
	db "JIGGLYPUFF"
	db "WIGGLYTUFF"
	db "ZUBAT@@@@@"
	db "GOLBAT@@@@"
	db "ODDISH@@@@"
	db "GLOOM@@@@@"
	db "VILEPLUME@"
	db "PARAS@@@@@"
	db "PARASECT@@"
	db "VENONAT@@@"
	db "VENOMOTH@@"
	db "DIGLETT@@@"
	db "DUGTRIO@@@"
	db "MEOWTH@@@@"
	db "PERSIAN@@@"
	db "PSYDUCK@@@"
	db "GOLDUCK@@@"
	db "MANKEY@@@@"
	db "PRIMEAPE@@"
	db "GROWLITHE@"
	db "ARCANINE@@"
	db "POLIWAG@@@"
	db "POLIWHIRL@"
	db "POLIWRATH@"
	db "ABRA@@@@@@"
	db "KADABRA@@@"
	db "ALAKAZAM@@"
	db "MACHOP@@@@"
	db "MACHOKE@@@"
	db "MACHAMP@@@"
	db "BELLSPROUT"
	db "WEEPINBELL"
	db "VICTREEBEL"
	db "TENTACOOL@"
	db "TENTACRUEL"
	db "GEODUDE@@@"
	db "GRAVELER@@"
	db "GOLEM@@@@@"
	db "PONYTA@@@@"
	db "RAPIDASH@@"
	db "SLOWPOKE@@"
	db "SLOWBRO@@@"
	db "MAGNEMITE@"
	db "MAGNETON@@"
	db "FARFETCH'D"
	db "DODUO@@@@@"
	db "DODRIO@@@@"
	db "SEEL@@@@@@"
	db "DEWGONG@@@"
	db "GRIMER@@@@"
	db "MUK@@@@@@@"
	db "SHELLDER@@"
	db "CLOYSTER@@"
	db "GASTLY@@@@"
	db "HAUNTER@@@"
	db "GENGAR@@@@"
	db "ONIX@@@@@@"
	db "DROWZEE@@@"
	db "HYPNO@@@@@"
	db "KRABBY@@@@"
	db "KINGLER@@@"
	db "VOLTORB@@@"
	db "ELECTRODE@"
	db "EXEGGCUTE@"
	db "EXEGGUTOR@"
	db "CUBONE@@@@"
	db "MAROWAK@@@"
	db "HITMONLEE@"
	db "HITMONCHAN"
	db "LICKITUNG@"
	db "KOFFING@@@"
	db "WEEZING@@@"
	db "RHYHORN@@@"
	db "RHYDON@@@@"
	db "CHANSEY@@@"
	db "TANGELA@@@"
	db "KANGASKHAN"
	db "HORSEA@@@@"
	db "SEADRA@@@@"
	db "GOLDEEN@@@"
	db "SEAKING@@@"
	db "STARYU@@@@"
	db "STARMIE@@@"
	db "MR.MIME@@@"
	db "SCYTHER@@@"
	db "JYNX@@@@@@"
	db "ELECTABUZZ"
	db "MAGMAR@@@@"
	db "PINSIR@@@@"
	db "TAUROS@@@@"
	db "MAGIKARP@@"
	db "GYARADOS@@"
	db "LAPRAS@@@@"
	db "DITTO@@@@@"
	db "EEVEE@@@@@"
	db "VAPOREON@@"
	db "JOLTEON@@@"
	db "FLAREON@@@"
	db "PORYGON@@@"
	db "OMANYTE@@@"
	db "OMASTAR@@@"
	db "KABUTO@@@@"
	db "KABUTOPS@@"
	db "AERODACTYL"
	db "SNORLAX@@@"
	db "ARTICUNO@@"
	db "ZAPDOS@@@@"
	db "MOLTRES@@@"
	db "DRATINI@@@"
	db "DRAGONAIR@"
	db "DRAGONITE@"
	db "MEWTWO@@@@"
	db "MEW@@@@@@@"
	db "PKMN 0×98@"
	db "PKMN 0×99@"
	db "PKMN 0×9A@"
	db "PKMN 0×9B@"
	db "PKMN 0×9C@"
	db "PKMN 0×9D@"
	db "PKMN 0×9E@"
	db "PKMN 0×9F@"
	db "PKMN 0×A0@"
	db "PKMN 0×A1@"
	db "PKMN 0×A2@"
	db "PKMN 0×A3@"
	db "PKMN 0×A4@"
	db "PKMN 0×A5@"
	db "PKMN 0×A6@"
	db "PKMN 0×A7@"
	db "PKMN 0×A8@"
	db "PKMN 0×A9@"
	db "PKMN 0×AA@"
	db "PKMN 0×AB@"
	db "PKMN 0×AC@"
	db "PKMN 0×AD@"
	db "PKMN 0×AE@"
	db "PKMN 0×AF@"
	db "PKMN 0×B0@"
	db "PKMN 0×B1@"
	db "PKMN 0×B2@"
	db "PKMN 0×B3@"
	db "PKMN 0×B4@"
	db "PKMN 0×B5@"
	db "PKMN 0×B6@"
	db "PKMN 0×B7@"
	db "PKMN 0×B8@"
	db "PKMN 0×B9@"
	db "PKMN 0×BA@"
	db "PKMN 0×BB@"
	db "PKMN 0×BC@"
	db "PKMN 0×BD@"
	db "PKMN 0×BE@"
	db "PKMN 0×BF@"
	db "PKMN 0×C0@"
	db "PKMN 0×C1@"
	db "PKMN 0×C2@"
	db "PKMN 0×C3@"
	db "PKMN 0×C4@"
	db "PKMN 0×C5@"
	db "PKMN 0×C6@"
	db "PKMN 0×C7@"
	db "PKMN 0×C8@"
	db "PKMN 0×C9@"
	db "PKMN 0×CA@"
	db "PKMN 0×CB@"
	db "PKMN 0×CC@"
	db "PKMN 0×CD@"
	db "PKMN 0×CE@"
	db "PKMN 0×CF@"
	db "PKMN 0×D0@"
	db "PKMN 0×D1@"
	db "PKMN 0×D2@"
	db "PKMN 0×D3@"
	db "PKMN 0×D4@"
	db "PKMN 0×D5@"
	db "PKMN 0×D6@"
	db "PKMN 0×D7@"
	db "PKMN 0×D8@"
	db "PKMN 0×D9@"
	db "PKMN 0×DA@"
	db "PKMN 0×DB@"
	db "PKMN 0×DC@"
	db "PKMN 0×DD@"
	db "PKMN 0×DE@"
	db "PKMN 0×DF@"
	db "PKMN 0×E0@"
	db "PKMN 0×E1@"
	db "PKMN 0×E2@"
	db "PKMN 0×E3@"
	db "PKMN 0×E4@"
	db "PKMN 0×E5@"
	db "PKMN 0×E6@"
	db "PKMN 0×E7@"
	db "PKMN 0×E8@"
	db "PKMN 0×E9@"
	db "PKMN 0×EA@"
	db "PKMN 0×EB@"
	db "PKMN 0×EC@"
	db "PKMN 0×ED@"
	db "PKMN 0×EE@"
	db "PKMN 0×EF@"
	db "PKMN 0×F0@"
	db "PKMN 0×F1@"
	db "PKMN 0×F2@"
	db "PKMN 0×F3@"
	db "PKMN 0×F4@"
	db "PKMN 0×F5@"
	db "PKMN 0×F6@"
	db "PKMN 0×F7@"
	db "PKMN 0×F8@"
	db "PKMN 0×F9@"
	db "PKMN 0×FA@"
	db "PKMN 0×FB@"
	db "PKMN 0×FC@"
	db "PKMN 0×FD@"
	db "PKMN 0×FE@"
	db "PKMN 0×FF@"
	db "PKMN 0×00@"
